### ISSUE TITLE
stETH Curve Pool LP strategy

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/yearn-strategies#11]
Description: deposit stETH/ETH Curve LP token and use gauge to earn rewards

Commit: [44549b96aa8d654862aadb1de7d863c367fecae9](https://github.com/Grandthrax/yearnv2_steth_crv_strat/commit/44549b96aa8d654862aadb1de7d863c367fecae9)

Repo: [stETHCurveStrategy](https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/master/contracts/Strategy.sol)

Last Commit Hash: [3ba7e3ce173aa356e34728413c9bf8e6974c0fec](https://github.com/Grandthrax/yearnv2_steth_crv_strat/commit/3ba7e3ce173aa356e34728413c9bf8e6974c0fec)

Review Completed By:

- [x] Doug
- [x] Orbxball

**Comment by dmolina79** [comment]
Question: 

https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/44549b96aa8d654862aadb1de7d863c367fecae9/contracts/Strategy.sol#L131

On this line to confirm, if `_debtOutstanding` = 10 and `_profit`= 10 the `_debtPayment` will be exactly 0 since we are checking balance and subtracting exactly the profit (which in this path is the same as balance)

It this expected?

**Comment by dmolina79** [comment]
Question:

Just to confirm, the strategy seeks to always invest all the want it has available correct?

https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/44549b96aa8d654862aadb1de7d863c367fecae9/contracts/Strategy.sol#L143

Just checking if there is any chance or combination where we could live want tokens in a `prepareMigration` here:

https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/44549b96aa8d654862aadb1de7d863c367fecae9/contracts/Strategy.sol#L143

Since it only accounts for balance on Gauge, so it must be sure that no leftover want tokens are left in the strategy balance correct?

**Comment by dmolina79** [comment]
Comment: 

Since we are handling different tokens, i guess slippage may impact profits if liquidity is shallow on uniswap for LDO and CRV

We use elsewhere a switch to change hardcoded exchanges.
https://github.com/iearn-finance/yearn-protocol/blob/52e8ce1c259db46081b8f622a699fa42cf8e0f87/contracts/strategies/StrategyCurveGUSDVoterProxy.sol#L101

But i guess since we are selling two tokens this may need different exchanges to get best price on LDO and CRV (possible that LDO has better liquidity in Sushi and CRV in Uniswap or vice versa)

**Comment by dmolina79** [comment]
Suggestion:

use steCrv as name for variable which is easier to understand than the one used.

address public constantCurveContractV3 =  address(0x06325440D014e39736583c165C2963BA99fAf14E);

**Comment by Grandthrax** [comment]
> On this line to confirm, if `_debtOutstanding` = 10 and `_profit`= 10 the `_debtPayment` will be exactly 0 since we are checking balance and subtracting exactly the profit (which in this path is the same as balance)
> 
> It this expected?

yes that's correct. We'd rather report profit than pay debt. The vault transfers all profit to it so you can't report a profit of more than want balance. Here's we'd report all profit.

**Comment by Grandthrax** [comment]
> Question:
> 
> Just to confirm, the strategy seeks to always invest all the want it has available correct?
> 
> https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/44549b96aa8d654862aadb1de7d863c367fecae9/contracts/Strategy.sol#L143

Yes I think you are right and I should remove this check. Always invest all even if there is debt outstanding. it will be dealt with in prepare return.

**Comment by Grandthrax** [comment]
> Comment:
> But i guess since we are selling two tokens this may need different exchanges to get best price on LDO and CRV (possible that LDO has better liquidity in Sushi and CRV in Uniswap or vice versa)

Yes valid point. I will create a switch to allow the changing of dex and/or route for both LDO and CRV.  Question is who should be allowed to do it? I assume just gov as you there may be a way to use it to drain funds.

**Comment by Grandthrax** [comment]
> constantCurveContractV3

I don't think I used it. Will remove. I used that name as that is what curve calls it.

**Comment by Grandthrax** [comment]
New commit with improvements:
https://github.com/Grandthrax/yearnv2_steth_crv_strat/commit/e6054be2393795ad466cb4be014520831827ea1b

Also added the code we use in zap to chose optimal routing for converting profit to stETH

**Comment by dmolina79** [comment]
> dex and/or route for both LDO and CRV. Question is who should be allowed to do it? I assume just gov as you there may be a way to use it to drain funds.

governance or strategist should work, since both dexes are hardcoded should be safe

**Comment by Grandthrax** [comment]
https://github.com/Grandthrax/yearnv2_steth_crv_strat/commit/ac6e1e521d52bb5c377e7e52d163d327ef976fa0

**Comment by dmolina79** [comment]
suggestion:

I think the setter should be a bool instead of an address

```
function switchDex(bool isUniswap) external {
        require(msg.sender == strategist || msg.sender == governance, "!authorized");
        if (isUniswap) {
            dex = uniswap;
        } else {
            dex = sushiswap;
        }
    }
    
    ```
    
    To be safe

**Comment by orbxball** [comment]
https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/ac6e1e521d52bb5c377e7e52d163d327ef976fa0/contracts/Strategy.sol#L127

the swap is weth, not eth right? how would there be eth?

**Comment by orbxball** [comment]
https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/ac6e1e521d52bb5c377e7e52d163d327ef976fa0/contracts/Strategy.sol#L133

```
stETH.submit{value: halfBal}(strategist);
```

is this one eth -> steth? what's the `strategist` for?

**Comment by orbxball** [comment]
```
function _estimateSell(address currency, uint256 amount) internal view returns (uint256 outAmount){
```

this might not be accurate. can only use it for reference.

**Comment by Grandthrax** [comment]
> https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/ac6e1e521d52bb5c377e7e52d163d327ef976fa0/contracts/Strategy.sol#L127
> 
> ```
> uint256 balance = address(this).balance;
> ```
> 
> the swap is weth, not eth right? how would there be eth?

no swap is eth

**Comment by Grandthrax** [comment]
> https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/ac6e1e521d52bb5c377e7e52d163d327ef976fa0/contracts/Strategy.sol#L133
> 
> ```
> stETH.submit{value: halfBal}(strategist);
> ```
> 
> is this one eth -> steth? what's the `strategist` for?

strategist is referal code. in future they might give rewards to people who referred but it is currently not used

**Comment by Grandthrax** [comment]
> ```
> function _estimateSell(address currency, uint256 amount) internal view returns (uint256 outAmount){
> ```
> 
> this might not be accurate. can only use it for reference.

not actually used anymore so will delete

**Comment by Grandthrax** [comment]
Final (hopefully) commit: https://github.com/Grandthrax/yearnv2_steth_crv_strat/commit/3ba7e3ce173aa356e34728413c9bf8e6974c0fec
